"""initial schema (spec §6)

Revision ID: 001
Revises: None
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('bytes_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('phash64', sa.String(length=16), nullable=True),
    sa.Column('pdq256', sa.String(length=64), nullable=True),
    sa.Column('video_frame_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simhash64', sa.String(length=16), nullable=True),
    sa.Column('c2pa_embedded', sa.Boolean(), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_phash64'), 'artifacts', ['phash64'], unique=False)
    op.create_index(op.f('ix_artifacts_sha256'), 'artifacts', ['sha256'], unique=False)
    op.create_table('entities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('regulator', 'exchange', 'listed_company', 'broker', 'mutual_fund', 'ria', name='entity_kind'), nullable=False),
    sa.Column('sebi_reg_no', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='entity_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('log_entries',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('leaf_hash', sa.String(length=64), nullable=False),
    sa.Column('entry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tree_size', sa.Integer(), nullable=False),
    sa.Column('root_hash', sa.String(length=64), nullable=False),
    sa.Column('sth_sig', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_seq'), 'log_entries', ['seq'], unique=True)
    op.create_table('scam_blacklist',
    sa.Column('kind', sa.Enum('domain', 'phash', 'phrase', name='blacklist_kind'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('campaign', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_domains',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('web', 'email', name='domain_kind'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('entity_sms_headers',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('header', sa.String(length=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header')
    )
    op.create_table('keys',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('maker', 'checker', 'entity', 'registry', name='key_role'), nullable=False),
    sa.Column('public_key_ed25519', sa.String(length=64), nullable=False),
    sa.Column('private_key_ed25519', sa.String(length=120), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', name='key_status'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.Enum('filing', 'sms', 'email', 'video', 'image', 'pdf', 'social', name='comm_channel'), nullable=False),
    sa.Column('impact', sa.Enum('standard', 'market_moving', name='comm_impact'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'maker_signed', 'published', 'revoked', name='comm_status'), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('maker_key_id', sa.UUID(), nullable=False),
    sa.Column('maker_sig', sa.String(length=120), nullable=True),
    sa.Column('checker_key_id', sa.UUID(), nullable=True),
    sa.Column('checker_sig', sa.String(length=120), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_seq', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['checker_key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['maker_key_id'], ['keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('channel', sa.Enum('sim', 'whatsapp', name='verify_channel'), nullable=False),
    sa.Column('input_kind', sa.Enum('image', 'video', 'pdf', 'text', 'url', 'eml', name='input_kind'), nullable=False),
    sa.Column('verdict', sa.Enum('VERIFIED', 'VERIFIED_NOTICE', 'OFFICIAL_CLAIM_UNVERIFIED', 'LIKELY_FAKE', 'INFORMATIONAL', name='verdict'), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_entity_id', sa.UUID(), nullable=True),
    sa.Column('matched_communication_id', sa.UUID(), nullable=True),
    sa.Column('claimed_entity_text', sa.String(length=300), nullable=True),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_communication_id'], ['communications.id'], ),
    sa.ForeignKeyConstraint(['matched_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verifications_created_at', 'verifications', ['created_at'], unique=False)
    op.create_table('view_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('communication_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_tokens')
    op.drop_index('ix_verifications_created_at', table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('communications')
    op.drop_table('keys')
    op.drop_table('entity_sms_headers')
    op.drop_table('entity_domains')
    op.drop_table('scam_blacklist')
    op.drop_index(op.f('ix_log_entries_seq'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_table('entities')
    op.drop_index(op.f('ix_artifacts_sha256'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_phash64'), table_name='artifacts')
    op.drop_table('artifacts')
    # postgres enum types are not dropped with their tables — drop explicitly
    for enum_name in (
        'entity_kind', 'entity_status', 'domain_kind', 'key_role', 'key_status',
        'comm_channel', 'comm_impact', 'comm_status', 'verify_channel',
        'input_kind', 'verdict', 'blacklist_kind',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
